image: node:14.16.0-buster

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cd post-service
    - npm install --force
    - npm run test

deploy:
  stage: deploy
  script: 
    - cd post-service
    - docker compose down
    - docker rmi post-service_post-service
    - docker build -t post-service .z