version: '3'

services:
  post-service:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - 3000:3000 
      
  post-service-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=post-service-database
    volumes:
      - ./data/db:/data/db
      - ./data/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - '27008:27008'

networks:
  default: 
      name: nexu_network
