FROM node:lts-alpine
WORKDIR /app
RUN apk add --no-cache curl \
    && curl -sL https://unpkg.com/@pnpm/self-installer | node
ENV NODE_ENV prod
USER root
COPY . ./
COPY package.json nest-cli.json pnpm-lock.yaml ../
RUN pnpm install --frozen-lockfile --prod
COPY ./src .
RUN pnpm run build
EXPOSE 3000
CMD ["pnpm", "run", "start:prod"]