apiVersion : apps/v1
kind: Deployment
metadata:
  name: "nexucluster-5ac0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nexucluster-5ac0"
  template:
    metadata:
      labels:
        app: "nexucluster-5ac0"
    spec:
      containers:
        - name: "nexucluster-5ac0"
          image: "s6nexu.azurecr.io/nexucluster"
          ports:
          - containerPort: 2000