apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "api-gateway"
    labels:
        app: "api-gateway"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:8080"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
    rules:
        - host: default-api-gateway.5521d5a114fc4eb38320.uksouth.aksapp.io
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: api-gateway
                  port:
                    number: 5000