apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "user-service"
    labels:
        app: "user-service"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: default-user-service.5521d5a114fc4eb38320.uksouth.aksapp.io
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: user-service
                  port:
                    number: 2000