apiVersion: v1
kind: Service
metadata:
    name: "nexucluster-5bd5"
    labels:
        app: "nexucluster-5bd5"
spec:
    type: ClusterIP
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "nexucluster-5bd5"