image: node:14.16.0-buster

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cd media-service
    - npm install --force
    - npm run test

deploy:
  stage: deploy
  script: 
    - cd media-service
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD docker.io
    - docker compose down
    - docker build -t $CI_REGISTRY_USER/media-service:latest .
    - docker push $CI_REGISTRY_USER/media-service:latest
  only: 
    - main