image: node:14.16.0-buster

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cd media-service
    - npm install
    - npm run test

deploy:
  stage: deploy
  script: 
    - cd media-service
    - docker compose down
    - docker rmi media-service_media-service
    - docker build -t media-service .