version: '3'

services:
  user-service:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - 2000:2000 
      
  user-service-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=user-service-database
    volumes:
      - ./data/db:/data/db
      - ./data/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - '27010:27010'

networks:
  default: 
      name: nexu_network
